DROP SEQUENCE seq_education;
DROP SEQUENCE seq_location;
DROP SEQUENCE seq_message;
DROP SEQUENCE seq_tag;

DROP TRIGGER tag_increment;
DROP TRIGGER education_increment;
DROP TRIGGER message_increment;
DROP TRIGGER location_increment;

DROP TABLE UserHasFriend;
Drop Table UserParticipatesInEvent;
DROP TABLE Tag CASCADE CONSTRAINTS;
DROP TABLE Photo CASCADE CONSTRAINTS;
DROP TABLE Message CASCADE CONSTRAINTS;
DROP TABLE Education CASCADE CONSTRAINTS;
DROP TABLE Event CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE FB_User CASCADE CONSTRAINTS;
