DROP SEQUENCE seq_education;
DROP SEQUENCE seq_location;
DROP SEQUENCE seq_message;
DROP SEQUENCE seq_tag;

DROP TRIGGER tag_increment;
DROP TRIGGER education_increment;
DROP TRIGGER message_increment;
DROP TRIGGER location_increment;
DROP TRIGGER photo_tag_relation;
DROP TRIGGER user_event_relation;
DROP TRIGGER insert_location_trigger;

DROP TABLE UserParticipatesInEvent;
DROP TABLE UserHasFriend;
DROP TABLE UserLivesInLocation;

DROP TABLE Tag CASCADE CONSTRAINTS;
DROP TABLE Photo CASCADE CONSTRAINTS;
DROP TABLE Message CASCADE CONSTRAINTS;
DROP TABLE Education CASCADE CONSTRAINTS;
DROP TABLE Event CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE FB_User CASCADE CONSTRAINTS;
