INSERT INTO FB_User (USER_ID, FIRST_NAME , LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER) SELECT USER_ID, FIRST_NAME , LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER FROM keykholt.PUBLIC_USER_INFORMATION;

INSERT INTO Event (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION) SELECT EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION FROM keykholt.PUBLIC_EVENT_INFORMATION;

INSERT INTO Location (CITY, STATE, COUNTRY, USER_ID)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, USER_ID FROM keykholt.PUBLIC_USER_INFORMATION
UNION
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, USER_ID FROM keykholt.PUBLIC_USER_INFORMATION
UNION 
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_ID FROM keykholt.PUBLIC_EVENT_INFORMATION;

INSERT INTO Education (USER_ID, PROGRAM_YEAR, INSTITUTION_NAME, PROGRAM_DEGREE, PROGRAM_CONCENTRATION) SELECT USER_ID, PROGRAM_YEAR, INSTITUTION_NAME, PROGRAM_DEGREE, PROGRAM_CONCENTRATION FROM keykholt.PUBLIC_USER_INFORMATION;


INSERT INTO Photo (ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_LINK) SELECT ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_LINK FROM keykholt.PUBLIC_PHOTO_INFORMATION;

INSERT INTO Tag (PHOTO_ID, TAG_SUBJECT_ID, TAG_X_COORDINATE, TAG_Y_COORDINATE) SELECT PHOTO_ID, TAG_SUBJECT_ID, TAG_X_COORDINATE, TAG_Y_COORDINATE FROM keykholt.PUBLIC_TAG_INFORMATION;

INSERT INTO UserHasFriend (USER1_ID, USER2_ID) SELECT USER1_ID, USER2_ID FROM keykholt.PUBLIC_ARE_FRIENDS;